- hosts: all
  vars:
    ubuntu_lts_release: bionic
    terraform_download_url: https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
    kubesec_download_url: https://github.com/shyiko/kubesec/releases/download/0.9.2/kubesec-0.9.2-linux-amd64
    stern_download_url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
    kubectx_download_url: https://github.com/ahmetb/kubectx/blob/v0.8.0/kubectx
    kubens_download_url: https://github.com/ahmetb/kubectx/blob/v0.8.0/kubens
    helm_download_url: https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
    eks_download_url: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
  become: yes
  roles:
    - setup
    - docker
    - npm
