- hosts: all
  vars:
    ubuntu_lts_release: bionic
    swap_file_size: 4G
    swap_file_path: /swap
    terraform_download_url: https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip
    kubesec_download_url: https://github.com/shyiko/kubesec/releases/download/0.9.2/kubesec-0.9.2-linux-amd64
    stern_download_url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
    kubectx_download_url: https://github.com/ahmetb/kubectx/releases/download/v0.9.0/kubectx
    kubens_download_url: https://github.com/ahmetb/kubectx/releases/download/v0.9.0/kubens
    helm_download_url: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
    kustomize_download_url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.5/kustomize_v3.5.5_linux_amd64.tar.gz
    ekscli_download_url: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
    ecscli_download_url: https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
    circleci_download_url: https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.6949/circleci-cli_0.1.6949_linux_amd64.tar.gz
    heroku_download_url: https://cli-assets.heroku.com/heroku-linux-x64.tar.gz
    dein_download_url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
  become: yes
  roles:
    - setup
    - docker
    - npm
    - go
    - pip3
    - vim
    - dotfiles
