- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop:
    - typescript
    - serverless
    - typescript-language-server
    - newman
    - redoc-cli
    - '@bitwarden/cli'
  ignore_errors: yes
