- name: Install go packages
  shell: go get -u "{{ item }}"
  loop:
    - github.com/monochromegane/the_platinum_searcher/...
    - golang.org/x/tools/cmd/goimports
    - github.com/golang/mock/gomock
    - github.com/golang/mock/mockgen
    - github.com/golang/protobuf/protoc-gen-go
    - github.com/favadi/protoc-go-inject-tag
    - github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    - github.com/fullstorydev/grpcurl
  register: shell_stdout
  become: no

- name: debug
  debug: 
    msg: "{{ shell_stdout }}"
